version: '3.1'

services:
  jenkins:
    build: .
    #image: jenkins/jenkins:jdk11
    container_name: v2_jenkins
    restart: on-failure
    ports:
      - "20000:8080"
    volumes:
      - º¼·ý¸í:/sharing/
      - /var/lib/docker/volumes/º¼·ý¸í/_data/jenkins/home/:/var/jenkins_home/
      - //var/run/docker.sock:/var/run/docker.sock
    user: root
    privileged: true

volumes:
    º¼·ý¸í:

networks:
  default:
    external:
      name: was-network