version: '3.1'

services:
  jenkins:
    build: .
    #image: jenkins/jenkins:jdk11
    container_name: v2_jenkins
    restart: on-failure
    ports:
      - "20000:8080"
    volumes:
      - orange_volume:/sharing/
      - //var/run/docker.sock:/var/run/docker.sock
    user: root
    privileged: true

volumes:
    orange_volume:

networks:
  default:
    external:
      name: was-network
